### ISSUE TITLE
Over brightening on some cosmetics

### ISSUE THREAD

**Issue by As0mn** [TF2CutContentWiki/HLMVPlusPlus-IssueTracker#1]
Title is the issue, for example on the Kringle Collection there's a part on the coat where it is too bright.
Image for this issue is here: 
https://steamuserimages-a.akamaihd.net/ugc/1903351281754719453/AB33FF62F38FD6162A12762C409024F7392B5647/

**Comment by TF2CutContentWiki** [comment]
Not sure if you're using the newest test build but give this one a try:

https://drive.google.com/file/d/1qZayqK4swrQx8gEzpUpqq4gCow-oa_aH/view?usp=drivesdk

**Comment by As0mn** [comment]
The test build fixed the issue, thank you!

**Comment by TF2CutContentWiki** [comment]
Beauty! Hope you enjoy the new test build 😊
